apiVersion: v1
kind: Service
metadata:
  name: wargameservice
spec:
  selector:
    # name: frontend
    # matchLabels:
    app: wargame
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: wargame
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      app: wargame
  #   tier: frontend
  template:
    metadata:
      name: frontend
      labels:
        tier: frontend
        app: wargame
    spec:
      containers:
      - name: apachehttp
        image: httpd
        ports:
        - containerPort: 80
